local M = {}

local function blend(fg, alpha, bg)
  return require('bonsai.theme').blend(fg, alpha, bg)
end

function M.get(c, opts)
  local transparent = opts.transparent

  -- stylua: ignore
  local hl = {
    -- Base editor highlights
    Comment                     = { fg = c.comment, style = opts.styles.comments },
    ColorColumn                 = { bg = c.black },
    Conceal                     = { fg = c.fg_gutter },
    Cursor                      = { fg = c.bg, bg = c.fg },
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorColumn                = { bg = c.bg_highlight },
    CursorLine                  = { bg = c.bg_highlight },
    Directory                   = { fg = c.blue },
    DiffAdd                     = { bg = c.diff.add },
    DiffChange                  = { bg = c.diff.change },
    DiffDelete                  = { bg = c.diff.delete },
    DiffText                    = { bg = c.diff.text },
    EndOfBuffer                 = { fg = c.bg },
    ErrorMsg                    = { fg = c.error },
    VertSplit                   = { fg = c.border },
    WinSeparator                = { fg = c.border, bold = true },
    Folded                      = { fg = c.blue, bg = c.fg_gutter },
    FoldColumn                  = { bg = transparent and c.none or c.bg, fg = c.comment },
    SignColumn                  = { bg = transparent and c.none or c.bg, fg = c.fg_gutter },
    SignColumnSB                = { bg = c.bg_sidebar, fg = c.fg_gutter },
    Substitute                  = { bg = c.red, fg = c.black },
    LineNr                      = { fg = c.fg_gutter },
    CursorLineNr                = { fg = c.cyan2, bold = true },
    LineNrAbove                 = { fg = c.fg_gutter },
    LineNrBelow                 = { fg = c.fg_gutter },
    MatchParen                  = { fg = c.orange, bold = true },
    ModeMsg                     = { fg = c.fg_dark, bold = true },
    MsgArea                     = { fg = c.fg_dark },
    MoreMsg                     = { fg = c.blue },
    NonText                     = { fg = c.border },
    Normal                      = { fg = c.fg, bg = transparent and c.none or c.bg },
    NormalNC                    = { fg = c.fg, bg = transparent and c.none or opts.dim_inactive and c.bg_dark or c.bg },
    NormalSB                    = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NormalFloat                 = { fg = c.fg, bg = c.bg_float },
    FloatBorder                 = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle                  = { fg = c.border_highlight, bg = c.bg_float },
    Pmenu                       = { bg = c.bg_popup, fg = c.fg },
    PmenuMatch                  = { bg = c.bg_popup, fg = c.cyan },
    PmenuSel                    = { bg = blend(c.fg_gutter, 0.8, c.bg) },
    PmenuMatchSel               = { bg = blend(c.fg_gutter, 0.8, c.bg), fg = c.cyan },
    PmenuSbar                   = { bg = blend(c.bg_popup, 0.95, c.fg) },
    PmenuThumb                  = { bg = c.fg_gutter },
    Question                    = { fg = c.blue },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.bg_search, fg = c.fg },
    IncSearch                   = { bg = c.orange, fg = c.black },
    CurSearch                   = 'IncSearch',
    SpecialKey                  = { fg = c.border },
    SpellBad                    = { sp = c.error, undercurl = true },
    SpellCap                    = { sp = c.warning, undercurl = true },
    SpellLocal                  = { sp = c.info, undercurl = true },
    SpellRare                   = { sp = c.hint, undercurl = true },
    StatusLine                  = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC                = { fg = c.fg_gutter, bg = c.bg_statusline },
    TabLine                     = { bg = c.bg_statusline, fg = c.fg_gutter },
    TabLineFill                 = { bg = transparent and c.none or c.black },
    TabLineSel                  = { fg = c.black, bg = c.cyan2 },
    Title                       = { fg = c.blue, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.warning },
    Whitespace                  = { fg = c.fg_gutter },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = 'StatusLine',
    WinBarNC                    = 'StatusLineNC',

    -- Syntax highlights
    Bold                        = { bold = true, fg = c.fg },
    Character                   = { fg = c.cyan1 },
    Constant                    = { fg = c.orange },
    Debug                       = { fg = c.orange },
    Delimiter                   = 'Special',
    Error                       = { fg = c.error },
    Function                    = { fg = c.blue2, style = opts.styles.functions },
    Identifier                  = { fg = c.fg, style = opts.styles.variables },
    Italic                      = { italic = true, fg = c.fg },
    Keyword                     = { fg = c.purple, style = opts.styles.keywords },
    Operator                    = { fg = c.fg_dark },
    PreProc                     = { fg = c.purple },
    Special                     = { fg = c.cyan },
    Statement                   = { fg = c.purple },
    String                      = { fg = c.cyan1 },
    Todo                        = { bg = c.yellow, fg = c.bg },
    Type                        = { fg = c.cyan },
    Underlined                  = { underline = true },
    debugBreakpoint             = { bg = blend(c.info, 0.1, c.bg), fg = c.info },
    debugPC                     = { bg = c.bg_sidebar },
    dosIniLabel                 = '@property',
    helpCommand                 = { bg = c.terminal_black, fg = c.blue },
    htmlH1                      = { fg = c.purple, bold = true },
    htmlH2                      = { fg = c.blue, bold = true },
    qfFileName                  = { fg = c.blue },
    qfLineNr                    = { fg = c.fg_gutter },
    Number                      = { fg = c.orange },
    Float                       = { fg = c.orange },
    Boolean                     = { fg = c.orange },

    -- LSP
    LspReferenceText            = { bg = c.fg_gutter },
    LspReferenceRead            = { bg = c.fg_gutter },
    LspReferenceWrite           = { bg = c.fg_gutter },
    LspSignatureActiveParameter = { bg = blend(c.bg_visual, 0.4, c.bg), bold = true },
    LspCodeLens                 = { fg = c.comment },
    LspInlayHint                = { bg = blend(c.teal, 0.1, c.bg), fg = c.comment },
    LspInfoBorder               = { fg = c.border_highlight, bg = c.bg_float },

    -- Diagnostics
    DiagnosticError             = { fg = c.error },
    DiagnosticWarn              = { fg = c.warning },
    DiagnosticInfo              = { fg = c.info },
    DiagnosticHint              = { fg = c.hint },
    DiagnosticUnnecessary       = { fg = c.terminal_black },
    DiagnosticVirtualTextError  = { bg = blend(c.error, 0.1, c.bg), fg = c.error },
    DiagnosticVirtualTextWarn   = { bg = blend(c.warning, 0.1, c.bg), fg = c.warning },
    DiagnosticVirtualTextInfo   = { bg = blend(c.info, 0.1, c.bg), fg = c.info },
    DiagnosticVirtualTextHint   = { bg = blend(c.hint, 0.1, c.bg), fg = c.hint },
    DiagnosticUnderlineError    = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn     = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo     = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint     = { undercurl = true, sp = c.hint },

    -- Health
    healthError                 = { fg = c.error },
    healthSuccess               = { fg = c.green },
    healthWarning               = { fg = c.warning },

    -- Diff
    diffAdded                   = { bg = c.diff.add, fg = c.git.add },
    diffRemoved                 = { bg = c.diff.delete, fg = c.git.delete },
    diffChanged                 = { bg = c.diff.change, fg = c.git.change },
    diffOldFile                 = { fg = c.blue, bg = c.diff.delete },
    diffNewFile                 = { fg = c.blue, bg = c.diff.add },
    diffFile                    = { fg = c.blue },
    diffLine                    = { fg = c.comment },
    diffIndexLine               = { fg = c.purple },
    helpExample                 = { fg = c.comment },

    -- Treesitter
    ['@annotation']                 = 'PreProc',
    ['@attribute']                  = 'PreProc',
    ['@boolean']                    = 'Boolean',
    ['@character']                  = 'Character',
    ['@character.printf']           = 'SpecialChar',
    ['@character.special']          = 'SpecialChar',
    ['@comment']                    = 'Comment',
    ['@comment.error']              = { fg = c.error },
    ['@comment.hint']               = { fg = c.hint },
    ['@comment.info']               = { fg = c.info },
    ['@comment.note']               = { fg = c.hint },
    ['@comment.todo']               = { fg = c.todo },
    ['@comment.warning']            = { fg = c.warning },
    ['@constant']                   = 'Constant',
    ['@constant.builtin']           = 'Special',
    ['@constant.macro']             = 'Define',
    ['@constructor']                = { fg = c.cyan },
    ['@constructor.tsx']            = { fg = c.cyan },
    ['@diff.delta']                 = 'DiffChange',
    ['@diff.minus']                 = 'DiffDelete',
    ['@diff.plus']                  = 'DiffAdd',
    ['@function']                   = 'Function',
    ['@function.builtin']           = 'Special',
    ['@function.call']              = '@function',
    ['@function.macro']             = 'Macro',
    ['@function.method']            = 'Function',
    ['@function.method.call']       = '@function.method',
    ['@keyword']                    = { fg = c.purple, style = opts.styles.keywords },
    ['@keyword.conditional']        = 'Conditional',
    ['@keyword.coroutine']          = '@keyword',
    ['@keyword.debug']              = 'Debug',
    ['@keyword.directive']          = 'PreProc',
    ['@keyword.directive.define']   = 'Define',
    ['@keyword.exception']          = 'Exception',
    ['@keyword.function']           = { fg = c.purple, style = opts.styles.functions },
    ['@keyword.import']             = 'Include',
    ['@keyword.operator']           = '@operator',
    ['@keyword.repeat']             = 'Repeat',
    ['@keyword.return']             = '@keyword',
    ['@keyword.storage']            = 'StorageClass',
    ['@label']                      = { fg = c.blue },
    ['@markup']                     = '@none',
    ['@markup.emphasis']            = { italic = true },
    ['@markup.environment']         = 'Macro',
    ['@markup.environment.name']    = 'Type',
    ['@markup.heading']             = 'Title',
    ['@markup.italic']              = { italic = true },
    ['@markup.link']                = { fg = c.cyan },
    ['@markup.link.label']          = 'SpecialChar',
    ['@markup.link.label.symbol']   = 'Identifier',
    ['@markup.link.url']            = 'Underlined',
    ['@markup.list']                = { fg = c.fg_dark },
    ['@markup.list.checked']        = { fg = c.green },
    ['@markup.list.markdown']       = { fg = c.orange, bold = true },
    ['@markup.list.unchecked']      = { fg = c.blue },
    ['@markup.math']                = 'Special',
    ['@markup.raw']                 = 'String',
    ['@markup.raw.markdown_inline'] = { bg = c.terminal_black, fg = c.blue },
    ['@markup.strikethrough']       = { strikethrough = true },
    ['@markup.strong']              = { bold = true },
    ['@markup.underline']           = { underline = true },
    ['@module']                     = 'Include',
    ['@module.builtin']             = { fg = c.red },
    ['@namespace.builtin']          = '@variable.builtin',
    ['@none']                       = {},
    ['@number']                     = 'Number',
    ['@number.float']               = 'Float',
    ['@operator']                   = { fg = c.fg_dark },
    ['@property']                   = { fg = c.cyan3 },
    ['@punctuation.bracket']        = { fg = c.fg_dark },
    ['@punctuation.delimiter']      = { fg = c.fg_dark },
    ['@punctuation.special']        = { fg = c.fg_dark },
    ['@punctuation.special.markdown'] = { fg = c.orange },
    ['@string']                     = 'String',
    ['@string.documentation']       = { fg = c.yellow },
    ['@string.escape']              = { fg = c.cyan1 },
    ['@string.regexp']              = { fg = c.magenta },
    ['@tag']                        = { fg = c.cyan },
    ['@tag.attribute']              = { fg = c.purple, italic = true },
    ['@tag.delimiter']              = 'Delimiter',
    ['@tag.delimiter.tsx']          = { fg = blend(c.blue, 0.7, c.bg) },
    ['@tag.tsx']                    = { fg = c.red },
    ['@tag.javascript']             = { fg = c.red },
    ['@type']                       = 'Type',
    ['@type.builtin']               = { fg = blend(c.cyan, 0.8, c.bg) },
    ['@type.definition']            = 'Typedef',
    ['@type.qualifier']             = '@keyword',
    ['@variable']                   = { fg = c.fg, style = opts.styles.variables },
    ['@variable.builtin']           = { fg = c.red },
    ['@variable.member']            = { fg = c.cyan3 },
    ['@variable.parameter']         = { fg = c.fg },
    ['@variable.parameter.builtin'] = { fg = blend(c.fg, 0.8, c.bg) },

    -- LSP semantic tokens
    ['@lsp.type.boolean']                      = '@boolean',
    ['@lsp.type.builtinType']                  = '@type.builtin',
    ['@lsp.type.comment']                      = '@comment',
    ['@lsp.type.decorator']                    = '@attribute',
    ['@lsp.type.deriveHelper']                 = '@attribute',
    ['@lsp.type.enum']                         = '@type',
    ['@lsp.type.enumMember']                   = { fg = c.pink },
    ['@lsp.type.escapeSequence']               = '@string.escape',
    ['@lsp.type.formatSpecifier']              = '@markup.list',
    ['@lsp.type.generic']                      = '@variable',
    ['@lsp.type.interface']                    = { fg = c.green2 },
    ['@lsp.type.keyword']                      = '@keyword',
    ['@lsp.type.lifetime']                     = '@keyword.storage',
    ['@lsp.type.namespace']                    = '@module',
    ['@lsp.type.namespace.python']             = '@variable',
    ['@lsp.type.number']                       = '@number',
    ['@lsp.type.operator']                     = '@operator',
    ['@lsp.type.parameter']                    = '@variable.parameter',
    ['@lsp.type.property']                     = '@property',
    ['@lsp.type.selfKeyword']                  = '@variable.builtin',
    ['@lsp.type.selfTypeKeyword']              = '@variable.builtin',
    ['@lsp.type.string']                       = '@string',
    ['@lsp.type.typeAlias']                    = '@type.definition',
    ['@lsp.type.unresolvedReference']          = { undercurl = true, sp = c.error },
    ['@lsp.type.variable']                     = {},
    ['@lsp.typemod.class.defaultLibrary']      = '@type.builtin',
    ['@lsp.typemod.enum.defaultLibrary']       = '@type.builtin',
    ['@lsp.typemod.enumMember.defaultLibrary'] = '@constant.builtin',
    ['@lsp.typemod.function.defaultLibrary']   = '@function.builtin',
    ['@lsp.typemod.keyword.async']             = '@keyword.coroutine',
    ['@lsp.typemod.keyword.injected']          = '@keyword',
    ['@lsp.typemod.macro.defaultLibrary']      = '@function.builtin',
    ['@lsp.typemod.method.defaultLibrary']     = '@function.builtin',
    ['@lsp.typemod.operator.injected']         = '@operator',
    ['@lsp.typemod.string.injected']           = '@string',
    ['@lsp.typemod.struct.defaultLibrary']     = '@type.builtin',
    ['@lsp.typemod.type.defaultLibrary']       = { fg = blend(c.cyan, 0.8, c.bg) },
    ['@lsp.typemod.typeAlias.defaultLibrary']  = { fg = blend(c.cyan, 0.8, c.bg) },
    ['@lsp.typemod.variable.callable']         = '@function',
    ['@lsp.typemod.variable.defaultLibrary']   = '@variable.builtin',
    ['@lsp.typemod.variable.injected']         = '@variable',
    ['@lsp.typemod.variable.static']           = '@constant',

    -- Completion item kinds
    CmpItemKindDefault          = { fg = c.fg_dark },
    CmpItemKindClass            = { fg = c.cyan },
    CmpItemKindColor            = { fg = c.cyan },
    CmpItemKindConstant         = { fg = c.orange },
    CmpItemKindConstructor      = { fg = c.cyan },
    CmpItemKindEnum             = { fg = c.cyan },
    CmpItemKindEnumMember       = { fg = c.pink },
    CmpItemKindEvent            = { fg = c.orange },
    CmpItemKindField            = { fg = c.cyan3 },
    CmpItemKindFile             = { fg = c.blue },
    CmpItemKindFolder           = { fg = c.blue },
    CmpItemKindFunction         = { fg = c.blue2 },
    CmpItemKindInterface        = { fg = c.green2 },
    CmpItemKindKeyword          = { fg = c.purple },
    CmpItemKindMethod           = { fg = c.blue2 },
    CmpItemKindModule           = { fg = c.cyan },
    CmpItemKindOperator         = { fg = c.fg_dark },
    CmpItemKindProperty         = { fg = c.cyan3 },
    CmpItemKindReference        = { fg = c.orange },
    CmpItemKindSnippet          = { fg = c.purple },
    CmpItemKindStruct           = { fg = c.cyan },
    CmpItemKindText             = { fg = c.fg_dark },
    CmpItemKindTypeParameter    = { fg = c.green2 },
    CmpItemKindUnit             = { fg = c.orange },
    CmpItemKindValue            = { fg = c.orange },
    CmpItemKindVariable         = { fg = c.fg },

    -- Telescope
    TelescopeNormal             = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder             = { fg = c.border_highlight, bg = c.bg_float },
    TelescopePromptNormal       = { bg = c.bg_float },
    TelescopePromptBorder       = { fg = c.border_highlight, bg = c.bg_float },
    TelescopePromptTitle        = { fg = c.bg, bg = c.cyan2 },
    TelescopePreviewTitle       = { fg = c.bg, bg = c.green },
    TelescopeResultsTitle       = { fg = c.bg_float, bg = c.bg_float },
    TelescopeMatching           = { fg = c.cyan },
    TelescopeSelection          = { bg = c.bg_highlight },

    -- Gitsigns
    GitSignsAdd                 = { fg = c.git.add },
    GitSignsChange              = { fg = c.git.change },
    GitSignsDelete              = { fg = c.git.delete },

    -- Indent Blankline
    IblIndent                   = { fg = c.border, nocombine = true },
    IblScope                    = { fg = c.cyan2, nocombine = true },

    -- Lazy
    LazyProgressDone            = { bold = true, fg = c.cyan2 },
    LazyProgressTodo            = { bold = true, fg = c.fg_gutter },

    -- Notify
    NotifyERRORBorder           = { fg = blend(c.error, 0.3, c.bg) },
    NotifyWARNBorder            = { fg = blend(c.warning, 0.3, c.bg) },
    NotifyINFOBorder            = { fg = blend(c.info, 0.3, c.bg) },
    NotifyDEBUGBorder           = { fg = c.border },
    NotifyTRACEBorder           = { fg = blend(c.purple, 0.3, c.bg) },
    NotifyERRORIcon             = { fg = c.error },
    NotifyWARNIcon              = { fg = c.warning },
    NotifyINFOIcon              = { fg = c.info },
    NotifyDEBUGIcon             = { fg = c.comment },
    NotifyTRACEIcon             = { fg = c.purple },
    NotifyERRORTitle            = { fg = c.error },
    NotifyWARNTitle             = { fg = c.warning },
    NotifyINFOTitle             = { fg = c.info },
    NotifyDEBUGTitle            = { fg = c.comment },
    NotifyTRACETitle            = { fg = c.purple },
    NotifyERRORBody             = 'Normal',
    NotifyWARNBody              = 'Normal',
    NotifyINFOBody              = 'Normal',
    NotifyDEBUGBody             = 'Normal',
    NotifyTRACEBody             = 'Normal',

    -- NeoTree
    NeoTreeNormal               = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeNormalNC             = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeDimText              = { fg = c.fg_gutter },
    NeoTreeGitAdded             = { fg = c.git.add },
    NeoTreeGitModified          = { fg = c.git.change },
    NeoTreeGitDeleted           = { fg = c.git.delete },
    NeoTreeGitUntracked         = { fg = c.green2 },
    NeoTreeIndentMarker         = { fg = c.border },
    NeoTreeRootName             = { fg = c.cyan2, bold = true },

    -- Which-key
    WhichKey                    = { fg = c.cyan },
    WhichKeyGroup               = { fg = c.blue },
    WhichKeyDesc                = { fg = c.fg_dark },
    WhichKeySeparator           = { fg = c.comment },
    WhichKeyValue               = { fg = c.fg_gutter },

    -- Dashboard / Alpha
    DashboardHeader             = { fg = c.cyan2 },
    DashboardFooter             = { fg = c.comment },
    DashboardCenter             = { fg = c.cyan },
    DashboardShortCut           = { fg = c.purple },

    -- Trouble
    TroubleNormal               = { fg = c.fg, bg = c.bg_sidebar },

    -- Flash
    FlashBackdrop               = { fg = c.comment },
    FlashLabel                  = { bg = c.cyan2, fg = c.bg, bold = true },

    -- Noice
    NoiceCmdlinePopupBorder     = { fg = c.border_highlight },
    NoiceCmdlinePopupTitle      = { fg = c.border_highlight },
    NoiceCmdlineIcon            = { fg = c.cyan2 },

    -- Mini
    MiniIndentscopeSymbol       = { fg = c.cyan2, nocombine = true },
    MiniStatuslineFilename      = { fg = c.fg_dark, bg = c.bg_statusline },
    MiniStatuslineInactive      = { fg = c.comment, bg = c.bg_statusline },
    MiniCursorword              = { bg = c.fg_gutter },

    -- Snacks
    SnacksIndent                = { fg = c.border, nocombine = true },
    SnacksIndentScope           = { fg = c.cyan2, nocombine = true },
    SnacksDashboardHeader       = { fg = c.cyan2 },
    SnacksDashboardFooter       = { fg = c.comment },
    SnacksDashboardDesc         = { fg = c.cyan },
    SnacksDashboardIcon         = { fg = c.cyan2 },
    SnacksDashboardKey          = { fg = c.orange },
    SnacksDashboardTitle        = { fg = c.cyan2, bold = true },
    SnacksDashboardSpecial      = { fg = c.purple },
    SnacksNotifierInfo          = { fg = c.info },
    SnacksNotifierWarn          = { fg = c.warning },
    SnacksNotifierError         = { fg = c.error },
    SnacksNotifierDebug         = { fg = c.comment },
    SnacksNotifierTrace         = { fg = c.purple },

    -- Blink.cmp
    BlinkCmpMenu                = { fg = c.fg, bg = c.bg_popup },
    BlinkCmpMenuBorder          = { fg = c.border_highlight, bg = c.bg_popup },
    BlinkCmpMenuSelection       = { bg = blend(c.fg_gutter, 0.8, c.bg) },
    BlinkCmpLabel               = { fg = c.fg },
    BlinkCmpLabelMatch          = { fg = c.cyan, bold = true },
    BlinkCmpKindDefault         = { fg = c.fg_dark },
    BlinkCmpKindClass           = { fg = c.cyan },
    BlinkCmpKindConstant        = { fg = c.orange },
    BlinkCmpKindConstructor     = { fg = c.cyan },
    BlinkCmpKindEnum            = { fg = c.cyan },
    BlinkCmpKindEnumMember      = { fg = c.pink },
    BlinkCmpKindField           = { fg = c.cyan3 },
    BlinkCmpKindFile            = { fg = c.blue },
    BlinkCmpKindFolder          = { fg = c.blue },
    BlinkCmpKindFunction        = { fg = c.blue2 },
    BlinkCmpKindInterface       = { fg = c.green2 },
    BlinkCmpKindKeyword         = { fg = c.purple },
    BlinkCmpKindMethod          = { fg = c.blue2 },
    BlinkCmpKindModule          = { fg = c.cyan },
    BlinkCmpKindOperator        = { fg = c.fg_dark },
    BlinkCmpKindProperty        = { fg = c.cyan3 },
    BlinkCmpKindSnippet         = { fg = c.purple },
    BlinkCmpKindStruct          = { fg = c.cyan },
    BlinkCmpKindText            = { fg = c.fg_dark },
    BlinkCmpKindTypeParameter   = { fg = c.green2 },
    BlinkCmpKindVariable        = { fg = c.fg },

    -- Rainbow delimiters
    RainbowDelimiterRed         = { fg = c.red },
    RainbowDelimiterYellow      = { fg = c.yellow },
    RainbowDelimiterBlue        = { fg = c.blue },
    RainbowDelimiterOrange      = { fg = c.orange },
    RainbowDelimiterGreen       = { fg = c.green },
    RainbowDelimiterViolet      = { fg = c.purple },
    RainbowDelimiterCyan        = { fg = c.cyan },
  }

  -- Markdown heading colors
  for i, color in ipairs(c.rainbow) do
    hl['@markup.heading.' .. i .. '.markdown'] = { fg = color, bold = true, bg = blend(color, 0.1, c.bg) }
  end

  return hl
end

return M
